## Spatial Data Science (GIS6307/GEO4930)


<br>
Instructor: Yi Qiang (qiangy@usf.edu)<br>
Teaching Assistant: Jinwen Xu (jinwenxu@usf.edu)

---

# Workshop on Spatial Analysis of Twitter

This workshop will help you to get started with the acquisition, processing, and analysis of Twitter data using data science techniques. Specifically, you will learn:

- Streaming real-time tweets using Twitter Developer APIs.
- Processing the raw tweets into an analyzable form.
- Basic mapping, spatial analysis and natural language processing for Twitter data.

### Prerequisite
- Install Anaconda in your computer.
- Activation of Twitter Developer Account and approved **Elevated Access** before the workshop.
- Basic programming skills are recommended, but not required.

## 1. Install Python Libraries

We will need two new libraries [tweepy](https://www.tweepy.org/) and [folium](https://plotly.com/python/) for this lab. Please do the following steps to install these two libarries.

1. Please open Anaconda Prompt, and use the command `conda activate geo` to activate the "geo" environment that you created in the previous lab. 

2. Install tweepy using the following command:

    `conda install -c conda-forge tweepy`
    
3. Install contextily using the following command:

    `conda install -c conda-forge folium`
    
4. Run the following code to import the installed libraries and other needed libraries. If the code runs through, the libraries are installed successfully.

In [1]:
# Run the following lines if there is an error loading basemap
# import os
# os.environ['PROJ_LIB'] = '~your anaconda 3 path/Anaconda3/Library/share/'

import tweepy
import folium
import pandas as pd

#from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt

## 2. Set-Up the Connection to Twitter APIs

Go to Twitter Developer Portal (https://developer.twitter.com/en/apps). Click the App you created in account activation.

If you haven't created an App when you created the account, you can create one in the project.

Click `Sign up`.

![](../image/twitter/signup3.jpg)

Turn on `OAuth 1.0a` and keep `OAuth 2.0` off. 

![](../image/twitter/OAuth.jpg)

Select "Read and write and Direct message". You can use "http://127.0.0.1:8080" as Callback URL. Add any website as the website URL (e.g. your personal website or https://google.com).

![](../image/twitter/setting.jpg)

Copy the API keys you have saved when you activated your Developer account, and paste them to replace "......" below. If you can't find them, you can **regenerate** the keys and tokens in your Developer Portal. 

![](../image/twitter/keys2.jpg)

Generate your Access Token and Secret and paste them below.

In [2]:
# paste your API keys and tokens to replace ......
# API_key = 'aOLqeAcCKvMRhKLZBIKADW2rW'
# API_key_secret = 'b1lOWTIy3Vfb5C2OS4S9wXP3BYzugrPs50i4oIqWmn1tcdORaT'
# access_token = '1508096832806731780-wIo5pKdrys6o1qoX7LETloH1tRirkS'
# access_token_secret = 'U4g0XQiGxGXnwN2Y5T2ePqKdxhS91jcHy2Zc5jqBEJ9V8'

API_key = 'gmDPt4mHl24zKIWeabwu1ebDs'
API_key_secret = '2Wx9lIi37wAH8oCHyS6Lw5dzboif7B8xxjMP3lnaGsKCIbtoEC'
access_token = '1343615702809374721-nBEV6K4qlSvkUFWpxhjn2Q3Gf5WpaL'
access_token_secret = 'z2dTOARM5FpdIMqOP9IzRwM9bzCvFNh9UhgvOD8WkquTc'

Set up for Twitter authentication.

In [3]:
auth = tweepy.OAuthHandler(API_key, API_key_secret)
auth.set_access_token(access_token, access_token_secret)

Set up tweepy API and set rate limit to be true.

In [4]:
api = tweepy.API(auth, wait_on_rate_limit=True)

---

## 3. Simple Operations with Twitter APIs

Now, your working environment is set up for Twitter analysis. Let's first try a few simple operations to acquire Twitter data in a programmatic way.

The full functionalities of Twitter API and Tweepy can be found in:

- [Twitter APIs](https://developer.twitter.com/en/docs.html)
- [Tweepy documentation](http://docs.tweepy.org/en/v4.8.0/)

### 3.1 Posting/Deleting a Tweet

First, let's post a message in your Twitter account.

**Note**: if you don't want to disturb your followers with a meanless tweet, don't run the following block of code.

In [5]:
# Post a tweet from Python
test_tweet = api.update_status("DRILL: I'm creating a robot to tweet!")

Check your Twitter account, and you'll see the above message is posted.

![](../image/twitter/tweet.jpg)


Tweets are encoded in a JSON (JavaScript Object Notation) format. You can run the following code to check the content of the tweet you just posted.

In [6]:
test_tweet._json

{'created_at': 'Thu Mar 31 01:38:35 +0000 2022',
 'id': 1509344371623149572,
 'id_str': '1509344371623149572',
 'text': "DRILL: I'm creating a robot to tweet!",
 'truncated': False,
 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []},
 'source': '<a href="https://google.com" rel="nofollow">GIS6307</a>',
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': None,
 'in_reply_to_user_id_str': None,
 'in_reply_to_screen_name': None,
 'user': {'id': 1343615702809374721,
  'id_str': '1343615702809374721',
  'name': 'alex',
  'screen_name': 'alex32348132',
  'location': '',
  'description': 'me',
  'url': None,
  'entities': {'description': {'urls': []}},
  'protected': False,
  'followers_count': 0,
  'friends_count': 9,
  'listed_count': 2,
  'created_at': 'Mon Dec 28 17:52:11 +0000 2020',
  'favourites_count': 1,
  'utc_offset': None,
  'time_zone': None,
  'geo_enabled': False,
  'verified': False,
  'statuses_count': 1,
  'lang': None,
  'contributors_enabled': False,
  'is_translator': False,
  'is_translation_enabled': False,
  'profile_background_color': 'F5F8FA',
  'profile_background_image_url': None,
  'profile_background_image_url_https': None,
  'profile_background_tile': False,
  'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
  'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png',
  'profile_link_color': '1DA1F2',
  'profile_sidebar_border_color': 'C0DEED',
  'profile_sidebar_fill_color': 'DDEEF6',
  'profile_text_color': '333333',
  'profile_use_background_image': True,
  'has_extended_profile': True,
  'default_profile': True,
  'default_profile_image': True,
  'following': False,
  'follow_request_sent': False,
  'notifications': False,
  'translator_type': 'none',
  'withheld_in_countries': []},
 'geo': None,
 'coordinates': None,
 'place': None,
 'contributors': None,
 'is_quote_status': False,
 'retweet_count': 0,
 'favorite_count': 0,
 'favorited': False,
 'retweeted': False,
 'lang': 'en'}

You can run the following code to delete the tweet you just posted.

In [7]:
api.destroy_status(test_tweet.id_str)

Status(_api=<tweepy.api.API object at 0x0000019E64F4BA00>, _json={'created_at': 'Thu Mar 31 01:38:35 +0000 2022', 'id': 1509344371623149572, 'id_str': '1509344371623149572', 'text': "DRILL: I'm creating a robot to tweet!", 'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []}, 'source': '<a href="https://google.com" rel="nofollow">GIS6307</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 1343615702809374721, 'id_str': '1343615702809374721', 'name': 'alex', 'screen_name': 'alex32348132', 'location': '', 'description': 'me', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 0, 'friends_count': 9, 'listed_count': 2, 'created_at': 'Mon Dec 28 17:52:11 +0000 2020', 'favourites_count': 1, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 1, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', 'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': True, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, 'geo': None, 'coordinates': None, 'place': None, 'contributors': None, 'is_quote_status': False, 'retweet_count': 0, 'favorite_count': 0, 'favorited': False, 'retweeted': False, 'lang': 'en'}, created_at=datetime.datetime(2022, 3, 31, 1, 38, 35, tzinfo=datetime.timezone.utc), id=1509344371623149572, id_str='1509344371623149572', text="DRILL: I'm creating a robot to tweet!", truncated=False, entities={'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []}, source='GIS6307', source_url='https://google.com', in_reply_to_status_id=None, in_reply_to_status_id_str=None, in_reply_to_user_id=None, in_reply_to_user_id_str=None, in_reply_to_screen_name=None, author=User(_api=<tweepy.api.API object at 0x0000019E64F4BA00>, _json={'id': 1343615702809374721, 'id_str': '1343615702809374721', 'name': 'alex', 'screen_name': 'alex32348132', 'location': '', 'description': 'me', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 0, 'friends_count': 9, 'listed_count': 2, 'created_at': 'Mon Dec 28 17:52:11 +0000 2020', 'favourites_count': 1, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 1, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', 'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': True, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, id=1343615702809374721, id_str='1343615702809374721', name='alex', screen_name='alex32348132', location='', description='me', url=None, entities={'description': {'urls': []}}, protected=False, followers_count=0, friends_count=9, listed_count=2, created_at=datetime.datetime(2020, 12, 28, 17, 52, 11, tzinfo=datetime.timezone.utc), favourites_count=1, utc_offset=None, time_zone=None, geo_enabled=False, verified=False, statuses_count=1, lang=None, contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='F5F8FA', profile_background_image_url=None, profile_background_image_url_https=None, profile_background_tile=False, profile_image_url='http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', profile_image_url_https='https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', profile_link_color='1DA1F2', profile_sidebar_border_color='C0DEED', profile_sidebar_fill_color='DDEEF6', profile_text_color='333333', profile_use_background_image=True, has_extended_profile=True, default_profile=True, default_profile_image=True, following=False, follow_request_sent=False, notifications=False, translator_type='none', withheld_in_countries=[]), user=User(_api=<tweepy.api.API object at 0x0000019E64F4BA00>, _json={'id': 1343615702809374721, 'id_str': '1343615702809374721', 'name': 'alex', 'screen_name': 'alex32348132', 'location': '', 'description': 'me', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 0, 'friends_count': 9, 'listed_count': 2, 'created_at': 'Mon Dec 28 17:52:11 +0000 2020', 'favourites_count': 1, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 1, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'F5F8FA', 'profile_background_image_url': None, 'profile_background_image_url_https': None, 'profile_background_tile': False, 'profile_image_url': 'http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', 'profile_image_url_https': 'https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': True, 'default_profile': True, 'default_profile_image': True, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, id=1343615702809374721, id_str='1343615702809374721', name='alex', screen_name='alex32348132', location='', description='me', url=None, entities={'description': {'urls': []}}, protected=False, followers_count=0, friends_count=9, listed_count=2, created_at=datetime.datetime(2020, 12, 28, 17, 52, 11, tzinfo=datetime.timezone.utc), favourites_count=1, utc_offset=None, time_zone=None, geo_enabled=False, verified=False, statuses_count=1, lang=None, contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='F5F8FA', profile_background_image_url=None, profile_background_image_url_https=None, profile_background_tile=False, profile_image_url='http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', profile_image_url_https='https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png', profile_link_color='1DA1F2', profile_sidebar_border_color='C0DEED', profile_sidebar_fill_color='DDEEF6', profile_text_color='333333', profile_use_background_image=True, has_extended_profile=True, default_profile=True, default_profile_image=True, following=False, follow_request_sent=False, notifications=False, translator_type='none', withheld_in_countries=[]), geo=None, coordinates=None, place=None, contributors=None, is_quote_status=False, retweet_count=0, favorite_count=0, favorited=False, retweeted=False, lang='en')

### 3.2 Getting Trending Tweets

Get the list of cities where trends are available

In [5]:
city_ls = api.available_trends()

Convert the list (in JSON format) into a dataframe (i.e. a table). Print the number of cities where trends are available.

In [6]:
df_city = pd.DataFrame(city_ls)

print (str(len(df_city)) + " cities have trends.")

467 cities have trends.

Preview 10 cities where trends are available

In [7]:
df_city.head(10)

,name,placeType,url,parentid,country,woeid,countryCode
0,Worldwide,"{'code': 19, 'name': 'Supername'}",http://where.yahooapis.com/v1/place/1,0,,1,None
1,Winnipeg,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2972,23424775,Canada,2972,CA
2,Ottawa,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/3369,23424775,Canada,3369,CA
3,Quebec,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/3444,23424775,Canada,3444,CA
4,Montreal,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/3534,23424775,Canada,3534,CA
5,Toronto,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/4118,23424775,Canada,4118,CA
6,Edmonton,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/8676,23424775,Canada,8676,CA
7,Calgary,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/8775,23424775,Canada,8775,CA
8,Vancouver,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/9807,23424775,Canada,9807,CA
9,Birmingham,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/12723,23424975,United Kingdom,12723,GB

Get the record of Tampa. The `woeid` is a unique ID for each place.

In [8]:
df_city[df_city['name']=='Tampa']

,name,placeType,url,parentid,country,woeid,countryCode
394,Tampa,"{'code': 7, 'name': 'Town'}",http://where.yahooapis.com/v1/place/2503863,23424977,United States,2503863,US

Store the `woeid` of Tampa in tampa_id.

In [14]:
tampa_id = df_city[df_city['name']=='Tampa']['woeid'].astype(int)

Return the trends in Tampa.

Note: you need to convert the city_id from a pandas series object into an integer.

In [10]:
# make Tampa as an example
trends_tampa = api.get_place_trends(int(tampa_id))

Print the trends in JSON format

In [11]:
# print the top 20 trends in Tampa
trends_tampa[0:20]

[{'trends': [{'name': '#Disney',
    'url': 'http://twitter.com/search?q=%23Disney',
    'promoted_content': None,
    'query': '%23Disney',
    'tweet_volume': 12925},
   {'name': '#GoBucs',
    'url': 'http://twitter.com/search?q=%23GoBucs',
    'promoted_content': None,
    'query': '%23GoBucs',
    'tweet_volume': None},
   {'name': '#TransDayOfVisibility',
    'url': 'http://twitter.com/search?q=%23TransDayOfVisibility',
    'promoted_content': None,
    'query': '%23TransDayOfVisibility',
    'tweet_volume': 57668},
   {'name': 'Wordle 285 X',
    'url': 'http://twitter.com/search?q=%22Wordle+285+X%22',
    'promoted_content': None,
    'query': '%22Wordle+285+X%22',
    'tweet_volume': None},
   {'name': '#TDOV',
    'url': 'http://twitter.com/search?q=%23TDOV',
    'promoted_content': None,
    'query': '%23TDOV',
    'tweet_volume': 22976},
   {'name': 'Daily Quordle 66',
    'url': 'http://twitter.com/search?q=%22Daily+Quordle+66%22',
    'promoted_content': None,
    'query': '%22Daily+Quordle+66%22',
    'tweet_volume': None},
   {'name': 'hyolyn',
    'url': 'http://twitter.com/search?q=hyolyn',
    'promoted_content': None,
    'query': 'hyolyn',
    'tweet_volume': 16190},
   {'name': 'LOONADOM BEGINS',
    'url': 'http://twitter.com/search?q=%22LOONADOM+BEGINS%22',
    'promoted_content': None,
    'query': '%22LOONADOM+BEGINS%22',
    'tweet_volume': 28323},
   {'name': 'Nipsey',
    'url': 'http://twitter.com/search?q=Nipsey',
    'promoted_content': None,
    'query': 'Nipsey',
    'tweet_volume': 10811},
   {'name': 'Transgender Day of Visibility',
    'url': 'http://twitter.com/search?q=%22Transgender+Day+of+Visibility%22',
    'promoted_content': None,
    'query': '%22Transgender+Day+of+Visibility%22',
    'tweet_volume': 15585},
   {'name': 'Happy Friday Eve',
    'url': 'http://twitter.com/search?q=%22Happy+Friday+Eve%22',
    'promoted_content': None,
    'query': '%22Happy+Friday+Eve%22',
    'tweet_volume': None},
   {'name': 'Good Thursday',
    'url': 'http://twitter.com/search?q=%22Good+Thursday%22',
    'promoted_content': None,
    'query': '%22Good+Thursday%22',
    'tweet_volume': 21368},
   {'name': 'Tom Hanks',
    'url': 'http://twitter.com/search?q=%22Tom+Hanks%22',
    'promoted_content': None,
    'query': '%22Tom+Hanks%22',
    'tweet_volume': None},
   {'name': 'George Clooney',
    'url': 'http://twitter.com/search?q=%22George+Clooney%22',
    'promoted_content': None,
    'query': '%22George+Clooney%22',
    'tweet_volume': None},
   {'name': 'April Fools',
    'url': 'http://twitter.com/search?q=%22April+Fools%22',
    'promoted_content': None,
    'query': '%22April+Fools%22',
    'tweet_volume': 53824},
   {'name': 'john mcclain',
    'url': 'http://twitter.com/search?q=%22john+mcclain%22',
    'promoted_content': None,
    'query': '%22john+mcclain%22',
    'tweet_volume': None},
   {'name': 'Clint Eastwood',
    'url': 'http://twitter.com/search?q=%22Clint+Eastwood%22',
    'promoted_content': None,
    'query': '%22Clint+Eastwood%22',
    'tweet_volume': None},
   {'name': 'Jared Leto',
    'url': 'http://twitter.com/search?q=%22Jared+Leto%22',
    'promoted_content': None,
    'query': '%22Jared+Leto%22',
    'tweet_volume': 15794},
   {'name': 'heejin',
    'url': 'http://twitter.com/search?q=heejin',
    'promoted_content': None,
    'query': 'heejin',
    'tweet_volume': 19686},
   {'name': 'Ivermectin',
    'url': 'http://twitter.com/search?q=Ivermectin',
    'promoted_content': None,
    'query': 'Ivermectin',
    'tweet_volume': 31048},
   {'name': 'Today is Thursday',
    'url': 'http://twitter.com/search?q=%22Today+is+Thursday%22',
    'promoted_content': None,
    'query': '%22Today+is+Thursday%22',
    'tweet_volume': None},
   {'name': 'Robin Williams',
    'url': 'http://twitter.com/search?q=%22Robin+Williams%22',
    'promoted_content': None,
    'query': '%22Robin+Williams%22',
    'tweet_volume': None},
   {'name': 'To Kill a Mockingbird',
    'url': 'http://twitter.com/search?q=%22To+Kill+a+Mockingbird%22',
    'promoted_content': None,
    'query': '%22To+Kill+a+Mockingbird%22',
    'tweet_volume': None},
   {'name': 'Christopher Walken',
    'url': 'http://twitter.com/search?q=%22Christopher+Walken%22',
    'promoted_content': None,
    'query': '%22Christopher+Walken%22',
    'tweet_volume': None},
   {'name': 'long live nip',
    'url': 'http://twitter.com/search?q=%22long+live+nip%22',
    'promoted_content': None,
    'query': '%22long+live+nip%22',
    'tweet_volume': None},
   {'name': 'Chernobyl',
    'url': 'http://twitter.com/search?q=Chernobyl',
    'promoted_content': None,
    'query': 'Chernobyl',
    'tweet_volume': 50038},
   {'name': 'Suisei',
    'url': 'http://twitter.com/search?q=Suisei',
    'promoted_content': None,
    'query': 'Suisei',
    'tweet_volume': 22304},
   {'name': 'Almost Friday',
    'url': 'http://twitter.com/search?q=%22Almost+Friday%22',
    'promoted_content': None,
    'query': '%22Almost+Friday%22',
    'tweet_volume': None},
   {'name': 'Blue Origin',
    'url': 'http://twitter.com/search?q=%22Blue+Origin%22',
    'promoted_content': None,
    'query': '%22Blue+Origin%22',
    'tweet_volume': None},
   {'name': 'Weird West',
    'url': 'http://twitter.com/search?q=%22Weird+West%22',
    'promoted_content': None,
    'query': '%22Weird+West%22',
    'tweet_volume': None},
   {'name': 'Mayagüez',
    'url': 'http://twitter.com/search?q=Mayag%C3%BCez',
    'promoted_content': None,
    'query': 'Mayag%C3%BCez',
    'tweet_volume': None},
   {'name': 'Buckhead',
    'url': 'http://twitter.com/search?q=Buckhead',
    'promoted_content': None,
    'query': 'Buckhead',
    'tweet_volume': None},
   {'name': 'Morbius',
    'url': 'http://twitter.com/search?q=Morbius',
    'promoted_content': None,
    'query': 'Morbius',
    'tweet_volume': 63029},
   {'name': 'Mick Mulvaney',
    'url': 'http://twitter.com/search?q=%22Mick+Mulvaney%22',
    'promoted_content': None,
    'query': '%22Mick+Mulvaney%22',
    'tweet_volume': 54448},
   {'name': 'Victory Lap',
    'url': 'http://twitter.com/search?q=%22Victory+Lap%22',
    'promoted_content': None,
    'query': '%22Victory+Lap%22',
    'tweet_volume': None},
   {'name': 'Ewan McGregor',
    'url': 'http://twitter.com/search?q=%22Ewan+McGregor%22',
    'promoted_content': None,
    'query': '%22Ewan+McGregor%22',
    'tweet_volume': None},
   {'name': 'Sally Field',
    'url': 'http://twitter.com/search?q=%22Sally+Field%22',
    'promoted_content': None,
    'query': '%22Sally+Field%22',
    'tweet_volume': None},
   {'name': 'Monaco',
    'url': 'http://twitter.com/search?q=Monaco',
    'promoted_content': None,
    'query': 'Monaco',
    'tweet_volume': 11360},
   {'name': 'Arians',
    'url': 'http://twitter.com/search?q=Arians',
    'promoted_content': None,
    'query': 'Arians',
    'tweet_volume': 43616},
   {'name': 'yves',
    'url': 'http://twitter.com/search?q=yves',
    'promoted_content': None,
    'query': 'yves',
    'tweet_volume': 21453},
   {'name': 'Steele',
    'url': 'http://twitter.com/search?q=Steele',
    'promoted_content': None,
    'query': 'Steele',
    'tweet_volume': 18426},
   {'name': 'Leonardo DiCaprio',
    'url': 'http://twitter.com/search?q=%22Leonardo+DiCaprio%22',
    'promoted_content': None,
    'query': '%22Leonardo+DiCaprio%22',
    'tweet_volume': None},
   {'name': 'Lovecraft Country',
    'url': 'http://twitter.com/search?q=%22Lovecraft+Country%22',
    'promoted_content': None,
    'query': '%22Lovecraft+Country%22',
    'tweet_volume': None},
   {'name': 'Draymond',
    'url': 'http://twitter.com/search?q=Draymond',
    'promoted_content': None,
    'query': 'Draymond',
    'tweet_volume': 10500},
   {'name': 'Klay',
    'url': 'http://twitter.com/search?q=Klay',
    'promoted_content': None,
    'query': 'Klay',
    'tweet_volume': 35794},
   {'name': 'The OA',
    'url': 'http://twitter.com/search?q=%22The+OA%22',
    'promoted_content': None,
    'query': '%22The+OA%22',
    'tweet_volume': None},
   {'name': 'Azuki',
    'url': 'http://twitter.com/search?q=Azuki',
    'promoted_content': None,
    'query': 'Azuki',
    'tweet_volume': 29025},
   {'name': 'Midwestern',
    'url': 'http://twitter.com/search?q=Midwestern',
    'promoted_content': None,
    'query': 'Midwestern',
    'tweet_volume': None},
   {'name': 'Steve McQueen',
    'url': 'http://twitter.com/search?q=%22Steve+McQueen%22',
    'promoted_content': None,
    'query': '%22Steve+McQueen%22',
    'tweet_volume': None}],
  'as_of': '2022-03-31T13:48:00Z',
  'created_at': '2022-03-29T11:28:46Z',
  'locations': [{'name': 'Tampa', 'woeid': 2503863}]}]

Organize the Tampa trends in a dataframe.

In [15]:
trend_ls = [[trend['name'], trend['url'], trend['tweet_volume']] for trend in trends_tampa[0]['trends']]

df_trends = pd.DataFrame(trend_ls,columns=['name','url','tweet_volume'])

Sort the trends by tweet volumn in a descending order and print the top 10 trends with the most tweeting volumne.

In [16]:
# Sort the trends by tweet volumn in a descending order
df_trends.sort_values("tweet_volume", inplace = True, ascending = False)

# Print the top 10 trends ranked by tweet volumne
df_trends.head(10)

            name                                             url  tweet_volume
48  Hunter Biden  http://twitter.com/search?q=%22Hunter+Biden%22      371961.0
2       Cawthorn            http://twitter.com/search?q=Cawthorn       90724.0
7         Ivanka              http://twitter.com/search?q=Ivanka       66687.0
5          Jared               http://twitter.com/search?q=Jared       50985.0
9   #AEWDynamite      http://twitter.com/search?q=%23AEWDynamite       43947.0
46          Tyga                http://twitter.com/search?q=Tyga       43731.0
42  The Get Down  http://twitter.com/search?q=%22The+Get+Down%22       42035.0
8        Booming             http://twitter.com/search?q=Booming       35092.0
40    Blac Chyna    http://twitter.com/search?q=%22Blac+Chyna%22       34045.0
37          Tori                http://twitter.com/search?q=Tori       33289.0

The table shows the popular topics people are tweeting about in Tampa.

---

## 4. Acquiring Tweets using the Search API

### 4.1 Search Tweets using Keywords

In this step, you will use Python program to search tweets that contain a specific keyword. "Will Smith" was quite a hot topic when I created the tutorial. Next, I will search for Tweets that contain "Will Smith".

In [17]:
tweets = api.search_tweets("Will Smith",count=100)

print("Total retweet retrieved: "+ str(len(tweets)))

Total retweet retrieved: 100

Store the user name, user location, posting time, and tweet text in a Pandas dataframe.

In [18]:
tweets_pd = pd.DataFrame([[tweet.user.name, tweet.user.location,tweet.created_at, tweet.text] for tweet in tweets], 
                         columns = ['user_name','user_loc','creation_time','text'])

tweets_pd

,user_name,user_loc,creation_time,text
0,Lenny Destefano,PCOLA In Da House,2022-03-31 01:38:53+00:00,"RT @JwinHitz: ""Will Smith set black people bac..."
1,TJP,,2022-03-31 01:38:53+00:00,@washingtonpost It was an ASSAULT…full stop🛑. ...
2,nalu kyle | The Batman 🦇❓,Gotham City,2022-03-31 01:38:52+00:00,RT @Venablewinters: The fact that this wasn‘t ...
3,TN,,2022-03-31 01:38:52+00:00,RT @kirstiealley: I don’t usually voice compla...
4,N W,UK,2022-03-31 01:38:52+00:00,@JenCrittenden @chrisrock #WillSmith #WillSmit...
...,...,...,...,...
95,Kate,,2022-03-31 01:38:38+00:00,RT @johnpavlovitz: Will Smith doesn't have to ...
96,Karøl 🦋 🏳️‍🌈,,2022-03-31 01:38:38+00:00,"RT @rafauccman: sei lá, as vezes eu entendo o ..."
97,dionidiaz,,2022-03-31 01:38:38+00:00,RT @CaraotaDigital: Jim Carrey cargó contra Wi...
98,Samantha Cook,,2022-03-31 01:38:38+00:00,"Open SmartNews and read ""Academy Begins Discip..."
99,Single FJB Mom x 2,California,2022-03-31 01:38:38+00:00,RT @RedWingGrips: The media has spent more tim...

The `search_tweets` funciton can retrieve max 100 tweets at one time. If you want to get more tweets, you can use the `cursor`.

The following code can retrieve more tweets containing a keyword. Here we still retrieve 100 tweets to save your search quota for the following steps. You could try to increase the `num` variable when testing at home.

> Note: You can only retrieve a limited number of tweets per 15 minutes. If the retrieved tweets exceed the limit, the program will pause for some time. If you can't wait, you can doublepress `i` on your keyboard to interrupt the process.

In [22]:
# Number of tweets to be retrieved.
num = 100

# define the search keyword
keyword = "Will Smith"

# use cursor to send your request with parameters
tweets = tweepy.Cursor(api.search_tweets,
                   q = keyword,
                   count = num,
                   lang="en").items(num)

# restore the results as a list
tweet_ls = [[tweet.user.name, tweet.user.location,tweet.created_at, tweet.text] for tweet in tweets]

# Store the retrieved tweets in a dataframe
tweets_pd_full = pd.DataFrame(tweet_ls, 
                         columns = ['user_name','user_loc','creation_time','text'])

# Print the dataframe
tweets_pd_full

,user_name,user_loc,creation_time,text
0,RussBrook,,2022-03-31 01:40:47+00:00,RT @BallsackSports: Damian Lillard commends Wi...
1,Luba Howard 🇺🇦,"Florida, USA",2022-03-31 01:40:46+00:00,"RT @NPR: Will Smith could face suspension, exp..."
2,Fibieie,Notifs set to mutuals only sry,2022-03-31 01:40:46+00:00,"RT @NoahPasternak: ""Garfield"" creator Jim Davi..."
3,Cares W,,2022-03-31 01:40:46+00:00,@pearce_manny @thebraingurl @CInroads @armanwa...
4,TrueBlueBroad,My Heart's In Boston,2022-03-31 01:40:45+00:00,"RT @__Arthur_Dent__: @kylegriffin1 ""We slipped..."
...,...,...,...,...
95,12tnob,,2022-03-31 01:40:27+00:00,RT @BreakingBrown: People wanna stand with Bla...
96,Flyinhigh☁️,Wildin🤪,2022-03-31 01:40:26+00:00,RT @ReciteSocial: @JoeDouble__U Your tweet was...
97,Nora,"Alabama, USA",2022-03-31 01:40:26+00:00,@mrstanlei The more I think about the worst it...
98,mm,"Birmingham, England",2022-03-31 01:40:26+00:00,"@Ocars @TheAcademy @RealWillSmith very funny, ..."
99,Dominic,California,2022-03-31 01:40:26+00:00,RT @OccupyDemocrats: BREAKING NEWS: The Oscars...

### 4.2 Removing Retweets
The retrieved tweets include original tweets and retweets. The textual content of retweets are almost identical. You can set up a filter to eliminate the retweets and keep only the original tweets.

In [20]:
new_keyword = "Will Smith" + " -filter:retweets"
new_keyword

'Will Smith -filter:retweets'

Now, you can see only original tweets are retrieved.

Print to see the list.

In [24]:
# Number of tweets to be retrieved.
num = 100

# use cursor to send your request with parameters
tweets = tweepy.Cursor(api.search_tweets,
                   q = new_keyword,
                   count = num,
                   lang="en").items(num)

# restore the results as a list
tweet_ls = [[tweet.user.name, tweet.user.location,tweet.created_at, tweet.text] for tweet in tweets]

# Store the retrieved tweets in a dataframe
tweets_pd_full = pd.DataFrame(tweet_ls, 
                         columns = ['user_name','user_loc','creation_time','text'])

# Print the dataframe
tweets_pd_full

,user_name,user_loc,creation_time,text
0,Brenda Gazzar,"Orange County, CA",2022-03-31 01:46:43+00:00,Was Will Smith's infamous Oscar slap a #trauma...
1,Peter Pandemic,"Toronto, Ontario",2022-03-31 01:46:41+00:00,The craziest thing about Will Smith is that he...
2,J.Bailey,,2022-03-31 01:46:40+00:00,Lawd! It ain’t Friday yet??? I swear this week...
3,Amaroq Softfur,In Mistress' lap 💙,2022-03-31 01:46:40+00:00,@DestruktorT Is that Will Smith using the tele...
4,David Willey,"California, USA",2022-03-31 01:46:39+00:00,@MeongEmpus #Will cuck Smith
...,...,...,...,...
95,Behan the Scene,VA,2022-03-31 01:45:49+00:00,@CultureCrave Suspending Will Smith for the ne...
96,Alisha,here and there,2022-03-31 01:45:49+00:00,@ricardojones05 @ZacEtheridge4 @S_Ruzic @Aubur...
97,Roger Wilhoit,"Illinois, USA",2022-03-31 01:45:49+00:00,"Ok, so I'm probably late to this party, but I ..."
98,Tim陳Chan,"Toronto, Ontario",2022-03-31 01:45:48+00:00,@FANEXPOCANADA Will Smith
99,Barry Bradford,"Deerfield, IL",2022-03-31 01:45:48+00:00,@TheLaydeeEve @snopes @willmckinley @DADiCleme...

### 4.3 Search Tweets using locations

Query for a popular trend keyword in Tampa (200 miles range).

First, let's check what are the top 10 trending topics in the selected city (Tampa).

The following code may take a few minutes to run to collect the tweets, depending on the number of tweets.

In [68]:
# Number of tweets to be retrieved.
num = 100

# define the search keyword
keyword = "Will Smith"

# use cursor to send your request with parameters
tweets = tweepy.Cursor(api.search_tweets,
                   q=keyword,
                   geocode = "28.0619,-82.4146,20mi",
                   count = num,
                   lang="en").items(num)

# restore the results as a list
tweet_ls = [[tweet.user.name, tweet.user.location, tweet.place, tweet.created_at, tweet.text] for tweet in tweets]

# Store the retrieved tweets in a dataframe
tweets_pd_geo = pd.DataFrame(tweet_ls, 
                         columns = ['user_name','user_loc','geotag','creation_time','text'])

# Print the dataframe
tweets_pd_geo

,user_name,user_loc,geotag,creation_time,text
0,tost,Tampa,None,2022-03-31 01:56:32+00:00,Chris Rock should double down and never talk a...
1,Bill Brasky,"Tampa, FL",None,2022-03-31 01:53:19+00:00,@monettem97 I actually don't know how I want S...
2,Ali Shakoor,"Tampa, Florida",None,2022-03-31 01:44:43+00:00,@JamesShawJr Important Will Smith content? Thi...
3,YOu dont need a feature? NIGGA IM THE FEATURE!!,"Clearwater, FL",None,2022-03-31 01:43:15+00:00,@j980 So to my understanding she shaded Will S...
4,Shamir Smith,"Brandon, Florida",None,2022-03-31 01:39:23+00:00,@DayDreamThis I mean I would rank it higher on...
...,...,...,...,...,...
95,Connie D...I ❤️ my kids and grands.,Tampa,None,2022-03-30 15:32:26+00:00,He ain't wong!\nhttps://t.co/a8fgZUMXEB
96,Allen,"Tampa, FL",None,2022-03-30 15:31:19+00:00,They should do a Rush Hour movie with Will Smi...
97,Tompa Bay Brady,"Tampa, FL",None,2022-03-30 15:09:58+00:00,@RealSkipBayless @undisputed there was no mali...
98,Josh Cate,"Tampa, Florida",None,2022-03-30 15:02:55+00:00,@nypost It seems the same people that call Kyl...
99,luï,Tampa,None,2022-03-30 15:02:43+00:00,We just gone ignore that will smith was at Eps...

Check how many tweets have geotags.

In [70]:
all_tweets = len(tweets_pd_geo[tweets_pd_geo['geotag'].notna()]) # all retrieved tweets
geo_tweets = len(tweets_pd_geo) # tweets that actually have geotags.

print("%s out of the %s retrieved tweets actually have geotags" % (all_tweets, geo_tweets))

4 out of the 100 retrieved tweets actually have geotags

#### Copy tweets with geotags to a new dataframe called "geotags"

In [78]:
geotags = df_result.loc[df_result['place'].notna()].copy()

#### get their place and view where first 5 tweets are from

In [79]:
geotags['place_name'] = geotags.place.apply(lambda s:s.name)

In [80]:
geotags.head()

,user,text,location,place,place_name
6,D3zMix,@alt_lyfe heavy out here in #pcb #coyoteugly ...,FL USA,Place(_api=<tweepy.api.API object at 0x0000025...,Panama City Beach
7,divinemoira,Swing through life as fearlessly as you did wh...,,Place(_api=<tweepy.api.API object at 0x0000025...,Sarasota
22,divinemoira,Dance with me… @ Lido Beach Resort https://t.c...,,Place(_api=<tweepy.api.API object at 0x0000025...,Sarasota
24,paulleary,"At Palm Beach Pride, 30 LGBTQ couples who marr...","Miami, FL",Place(_api=<tweepy.api.API object at 0x0000025...,Fort Lauderdale
27,MrsGinaC,Delicious blackened sea food platter and muscl...,"Oswego, IL",Place(_api=<tweepy.api.API object at 0x0000025...,Aunt Kate's

#### Check place information and parse them into dataframe

In [81]:
geotags.place[min(geotags.index)]

Place(_api=<tweepy.api.API object at 0x00000254C2A7A3D0>, id='9ebd5acfac2301ba', url='https://api.twitter.com/1.1/geo/id/9ebd5acfac2301ba.json', place_type='city', name='Panama City Beach', full_name='Panama City Beach, FL', country_code='US', country='United States', contained_within=[], bounding_box=BoundingBox(_api=<tweepy.api.API object at 0x00000254C2A7A3D0>, type='Polygon', coordinates=[[[-85.95802, 30.1650609], [-85.7860766, 30.1650609], [-85.7860766, 30.266595], [-85.95802, 30.266595]]]), attributes={})

#### Print the bounding box of the geotag

In [82]:
geotags.place[min(geotags.index)].bounding_box

BoundingBox(_api=<tweepy.api.API object at 0x00000254C2A7A3D0>, type='Polygon', coordinates=[[[-85.95802, 30.1650609], [-85.7860766, 30.1650609], [-85.7860766, 30.266595], [-85.95802, 30.266595]]])

###### Print the coordinates of the bounding box

In [83]:
geotags.place[min(geotags.index)].bounding_box.coordinates[0]

[[-85.95802, 30.1650609],
 [-85.7860766, 30.1650609],
 [-85.7860766, 30.266595],
 [-85.95802, 30.266595]]

#### Generate a column called bounding_box to restore bounding box information

In [84]:
geotags['bounding_box'] = geotags.place.apply(lambda s:s.bounding_box.coordinates[0])

In [85]:
geotags.head()

,user,text,location,place,place_name,bounding_box
6,D3zMix,@alt_lyfe heavy out here in #pcb #coyoteugly ...,FL USA,Place(_api=<tweepy.api.API object at 0x0000025...,Panama City Beach,"[[-85.95802, 30.1650609], [-85.7860766, 30.165..."
7,divinemoira,Swing through life as fearlessly as you did wh...,,Place(_api=<tweepy.api.API object at 0x0000025...,Sarasota,"[[-82.588866, 27.293114], [-82.477281, 27.2931..."
22,divinemoira,Dance with me… @ Lido Beach Resort https://t.c...,,Place(_api=<tweepy.api.API object at 0x0000025...,Sarasota,"[[-82.588866, 27.293114], [-82.477281, 27.2931..."
24,paulleary,"At Palm Beach Pride, 30 LGBTQ couples who marr...","Miami, FL",Place(_api=<tweepy.api.API object at 0x0000025...,Fort Lauderdale,"[[-80.20811, 26.080935], [-80.0902351, 26.0809..."
27,MrsGinaC,Delicious blackened sea food platter and muscl...,"Oswego, IL",Place(_api=<tweepy.api.API object at 0x0000025...,Aunt Kate's,"[[-81.31005883828144, 29.949614861868813], [-8..."

#### Parse the latitude and longitude hidden in the bounding box, finally check the dataframe

Store the centroids in a column 'point'

In [86]:
geotags['point']  = geotags['bounding_box'].apply(lambda s: [(s[0][1]+s[2][1])/2,(s[0][0]+s[2][0])/2])

Store the latitude of the centroids in the column 'lat'

In [87]:
geotags['lat']  = geotags['bounding_box'].apply(lambda s: (s[0][1]+s[2][1])/2)

Store the longitude of the centroids in the column 'lon'

In [88]:
geotags['lon']  = geotags['bounding_box'].apply(lambda s: (s[0][0]+s[2][0])/2)

Print to see the dataframe again.

You'll see the centroids, latitude, and longitude are added as columns in the dataframe.

Note: the point column is an redundancy of the lat and lon columns. We create all these columns just for demonstration of mapping in the next step.

In [89]:
geotags.head()

,user,text,location,place,place_name,bounding_box,point,lat,lon
6,D3zMix,@alt_lyfe heavy out here in #pcb #coyoteugly ...,FL USA,Place(_api=<tweepy.api.API object at 0x0000025...,Panama City Beach,"[[-85.95802, 30.1650609], [-85.7860766, 30.165...","[30.215827949999998, -85.8720483]",30.215828,-85.872048
7,divinemoira,Swing through life as fearlessly as you did wh...,,Place(_api=<tweepy.api.API object at 0x0000025...,Sarasota,"[[-82.588866, 27.293114], [-82.477281, 27.2931...","[27.3411215, -82.5330735]",27.341121,-82.533074
22,divinemoira,Dance with me… @ Lido Beach Resort https://t.c...,,Place(_api=<tweepy.api.API object at 0x0000025...,Sarasota,"[[-82.588866, 27.293114], [-82.477281, 27.2931...","[27.3411215, -82.5330735]",27.341121,-82.533074
24,paulleary,"At Palm Beach Pride, 30 LGBTQ couples who marr...","Miami, FL",Place(_api=<tweepy.api.API object at 0x0000025...,Fort Lauderdale,"[[-80.20811, 26.080935], [-80.0902351, 26.0809...","[26.150368, -80.14917255]",26.150368,-80.149173
27,MrsGinaC,Delicious blackened sea food platter and muscl...,"Oswego, IL",Place(_api=<tweepy.api.API object at 0x0000025...,Aunt Kate's,"[[-81.31005883828144, 29.949614861868813], [-8...","[29.949614861868813, -81.31005883828144]",29.949615,-81.310059

---

## 4. Spatial visualization using folium package

Import the folium package to create an interactive map.

In [90]:
import folium

Create a basemap.

In [91]:
#oahu = folium.Map(location = [21.473,-157.9868],zoom_start = 10)
maptweet = folium.Map()

Add the tweets into the basemap

In [92]:
for i, row in geotags.iterrows():
    folium.Marker(row.point,popup = row.text).add_to(maptweet)

Zoom closer into the tweets

In [93]:
maptweet.fit_bounds([[min(geotags.lat),min(geotags.lon)],[max(geotags.lat),max(geotags.lon)]])

In [94]:
display(maptweet)